name: ${pluginName}
version: ${version}
main: ${group}.${packageName}.plugin.${pluginName}Plugin
api-version: 1.20
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.21
  - org.jetbrains.kotlin:kotlin-reflect:1.9.21
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3
  - io.github.monun:tap:4.9.8
  - io.github.monun:kommand:3.1.7
  - io.github.monun:heartbeat-coroutines:0.0.5